#!/bin/bash -l
#PBS -S /bin/bash
#PBS -A GT-jkretchmer3-chemx
#PBS -l nodes=1:ppn=1

#PBS -l walltime=1:00:00
#PBS -N tdhf_N12
#PBS -e pbs_error_file.err
#PBS -o pbs_output_file.out
#PBS -V

cd $PBS_O_WORKDIR
module load anaconda3
conda activate pyscf_env
python3 run_tdhf.py > dariia.out
